language: r 

os:
  - linux

sudo: required
dist: precise
group: edge

r_build_args: "--resave-data --compact-vignettes=gs+qpdf"
r_check_args: "--as-cran --timings"
cran: "http://cran.r-project.org"

apt_packages:
  - latex-xcolor
  - texlive-latex3 # attempt to fix mathtools.sty not found error

r_binary_packages:
  - vegan
  - ggplot2
  - reshape2
  - dplyr
  - boot
  - shiny
  - testthat
  - knitr
  - rmarkdown
  - knitcitations
  - poweRlaw

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
    - NOT_CRAN: true
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
